### ISSUE TITLE
Nodes connected to senders sometimes stick an image preview in them, even when not an image node (int, simple string)? Weird. 

### ISSUE THREAD

**Issue by aegis72** [chrisgoringe/cg-use-everywhere#96] opened 2024-01-16 23:27 UTC
Weird display bug with Simple String. Node somehow picks up an image from a previous generation; not sure why it picks one up at all :).

 
![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/118572301/e43dc573-54dd-44e1-9bf5-5154a2c9e64c)

here's another example, so might have nothing to do with you after all...this is an int literal connected to a sender (left).
![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/118572301/a46a8abc-7d92-4d88-aaed-225df765e920)

![sd15+Setup](https://github.com/chrisgoringe/cg-use-everywhere/assets/118572301/af72ea97-6ca0-4f31-bf57-8be0045127d9)
WF is above.

**Comment by chrisgoringe** [comment] 2024-01-21 22:09
Pretty sure this isn't being caused by UE - or rather, that it's an interaction with another node that is misbehaving. If you can work out what other node, I will work with that developer to fix. In the meantime I'm closing this as not a UE issue.

**Closed by chrisgoringe** 2024-01-21 22:09 UTC

**Comment by aegis72** [comment] 2024-01-22 14:23
yeah, makes sense i will try to track it down
