### ISSUE TITLE
This node conflicts with the default ‘preset node’ of comfyui, resulting in a pop-up prompt when opening a workflow containing a preset node. The pop-up cannot be closed and can only be solved by deleting the node.

### ISSUE THREAD

**Issue by yhgszi** [chrisgoringe/cg-use-everywhere#105] opened 2024-01-31 06:47 UTC
![screenshot-20240131-144225](https://github.com/chrisgoringe/cg-use-everywhere/assets/34730193/3800dc23-165f-46db-8b1f-624991bbf2ee)
![screenshot-20240131-144329](https://github.com/chrisgoringe/cg-use-everywhere/assets/34730193/0c3248d7-ad19-41e8-9c62-75b904cb4543)
After clicking OK on this pop-up box, it still prompts and cannot be closed.

**Comment by chrisgoringe** [comment] 2024-01-31 07:36
I don't think that's a default node - the snake icon on the title bar makes me think it is one of pyhtonsssss nodes.

Could you please confirm the node which causes the conflict and I will investigate.

**Comment by yhgszi** [comment] 2024-01-31 10:09
thank you for your reply. Other plug-ins currently installed will not conflict when opening the process of this node. However, after installing this node, a pop-up prompt will appear when opening it. Please check it out and try to reproduce it.

**Comment by chrisgoringe** [comment] 2024-01-31 10:46
After installing use everything nodes, you mean?

But I've never seen the problem, so there must be an interaction with another custom node.

Can you tell me what custom node pack the node with the snake on is from?

**Comment by yhgszi** [comment] 2024-01-31 12:12
https://github.com/pythongosssss/ComfyUI-Custom-Scripts

You can find it here,thanks

**Comment by chrisgoringe** [comment] 2024-03-18 05:32
Can't reproduce the exact error, but there is an issue that I have raised as #154 

I'm closing this as not reproduceable - please reopen (or open a new issue) if you are still able to reproduce the error (ideally with a simple workflow that illustrates it!)

**Closed by chrisgoringe** 2024-03-18 05:32 UTC
Labels: compatibility
