### ISSUE TITLE
Cannot be converted to group node

### ISSUE THREAD

**Issue by mijuku233** [chrisgoringe/cg-use-everywhere#102] opened 2024-01-25 03:21 UTC
When `everywhere` is converted into a group node, it will lose its function.

**Comment by mijuku233** [comment] 2024-01-25 03:29
Maybe this bug is quite tricky? Is it possible to fix it?

**Comment by chrisgoringe** [comment] 2024-01-25 03:50
At first look it seems very unlikely this will be fixed. It is mentioned in the ReadMe. But I might look again once the group node code in the ComfyUI base is more stable.

This is a limitation, not a bug!

**Comment by chrisgoringe** [comment] 2024-02-26 22:09
Apparently a UE node in a group still works (according to #109). Maybe you can see if it works for you?

**Comment by mijuku233** [comment] 2024-02-27 02:20
> Apparently a UE node in a group still works (according to #109). Maybe you can see if it works for you?

After my testing, "UE nodes work when converted to group nodes" is just an illusion.

I created a similar workflow and ran it, `show text` shows that `required input` is missing.
![屏幕截图 2024-02-27 095939](https://github.com/chrisgoringe/cg-use-everywhere/assets/89350747/7b92447a-b831-4111-a7c6-9c8287dfb608)
![屏幕截图 2024-02-27 100015](https://github.com/chrisgoringe/cg-use-everywhere/assets/89350747/07894876-acde-4302-8aaa-561c06ea177e)


When I first output text to `show text`, then convert to group node
![屏幕截图 2024-02-27 100055](https://github.com/chrisgoringe/cg-use-everywhere/assets/89350747/ca337bda-a1b3-4407-aee3-04cfd7f943fe)


and then modify the text, `show text` still shows the previous text, not the new one!
![屏幕截图 2024-02-27 100425](https://github.com/chrisgoringe/cg-use-everywhere/assets/89350747/d1458ebe-3c57-4df8-8465-3b7e776dd855)


The reason for the illusion seems to be that `show text` takes the previously received text as input.

**Comment by chrisgoringe** [comment] 2024-03-03 01:31
Now working! Please open new issue for any problems

**Closed by chrisgoringe** 2024-03-03 01:31 UTC
Labels: enhancement, question
