### ISSUE TITLE
High CPU and GPU usage

### ISSUE THREAD

**Issue by Firetheft** [chrisgoringe/cg-use-everywhere#149] opened 2024-03-17 03:15 UTC
In recent comfyui, if you use this node, you will find that the CPU and GPU usage is high, and the FPS in the lower left corner is jumping wildly. If you delete this node, the situation will return to normal immediately.

**Comment by chrisgoringe** [comment] 2024-03-17 04:19
Duplicate of #146

**Closed** 2024-03-17 04:19 UTC

**Comment by chrisgoringe** [comment] 2024-03-17 04:30
See comments on #146 for update
