### ISSUE TITLE
problem with text widget clip text encode prompt and c comments

### ISSUE THREAD

**Issue by tester4488** [chrisgoringe/cg-use-everywhere#186] opened 2024-04-15 10:34 UTC
if i put a //
or /* text */
it no longer lets me edit the text, it moves the cursor to the end.

![322218147-d3990baa-6501-449e-813f-9dbb0ed7392c](https://github.com/chrisgoringe/cg-use-everywhere/assets/160387045/d51eda95-e313-4f46-9241-a0b73c43e917)

https://github.com/comfyanonymous/ComfyUI/issues/3261
uninstalling the extension, all works normal

**Comment by chrisgoringe** [comment] 2024-04-15 12:57
duplicate of #172

**Closed** 2024-04-15 12:58 UTC
